# @no-cookie-jar
#POST http://localhost:8080/api/v1/auth/register
#Content-Type: application/json
#
#{
#  "username": "shanky",
#  "email": "shaky@gmail.com",
#  "password": "123456"
#}

### Login User
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "yatharth",
    "password": "123456"
}

#### Create Category
#@jwt = {{login.response.body.data.token}}
#@userId = {{login.response.body.data.userId}}
#POST http://localhost:8080/api/v1/category/create
#Authorization: Bearer {}
#Content-Type: application/json
#
#{
#  "name": "Food",
#  "type": "EXPENSE"
#}
#
#### Get All Categories
#GET http://localhost:8080/api/v1/category
#Authorization: Bearer {{jwt}}
